### ISSUE TITLE
Clippy lints

### ISSUE THREAD

**Issue by oxarbitrage** [Renmusxd/RustQIP#28]
Tried to run clippy in the repo and there are a lot of lints, we should try to fix it as it will allow developers to merge better code.

Will be nice if the following command passes without warnings or errors at some time in the future:

```
cargo clippy --all-features --all-targets
```

**Comment by Renmusxd** [comment]
Ah, I had been running clippy without `--all-targets` so missed all these. I'll start going through them.

**Comment by Renmusxd** [comment]
Fixed in 2755a6c and 4c4eba8

**Comment by oxarbitrage** [comment]
Awesome, thanks.
